The image cover was added in the detail
wolox-training/jq-angular pull request #4
Opened 2019-11-07 16:05 UTC by pabloqv10

## Summary

- The detail of book was implemented

## Trello Card

[https://trello.com/c/xOFmaf4z/26-detalle-de-libro-i-textos](url)

## Screenshot
<img width="1680" alt="detail-2-image" src="https://user-images.githubusercontent.com/13438797/68405649-7b8aeb00-014e-11ea-8400-d879acc61bd2.png">

2019-11-07 17:25 UTC, manueltuero requested changes

2019-11-07 17:25 UTC, manueltuero commented on scss/detail.scss
> +}
Add a new empty line here.

2019-11-07 17:25 UTC, manueltuero commented on index.html
> +      <div class="row">
Maybe you can avoid using a div like a separator. Using **margin** for example.

2019-11-07 17:25 UTC, manueltuero commented on index.html
> +      <img src="./assets/book-cover.png" alt="book-cover" class="book-cover">
You can write a normal text in the **alt** attribute. E.g.: **"Book cover"**

2019-11-07 17:25 UTC, manueltuero commented on index.html
> +          <h3 class="author">Autor del libro:</h3>
I don't think that must use an h3 tag here

2019-11-08 19:36 UTC, Dorian30 approved these changes

2019-11-11 17:23 UTC, manueltuero approved these changes

2019-11-12 14:37 UTC, merged